/*
*   2. SQL Queries
*/

--2.1 SELECT
SELECT * FROM EMPLOYEE;
SELECT * FROM EMPLOYEE WHERE LASTNAME='King';
SELECT * FROM EMPLOYEE WHERE FIRSTNAME='Andrew' AND REPORTSTO IS NULL;

--2.2 ORDER BY
SELECT * FROM ALBUM ORDER BY TITLE DESC;
SELECT FIRSTNAME FROM CUSTOMER ORDER BY CITY ASC;

--2.3 INSERT INTO
INSERT INTO GENRE VALUES (26, 'Alt Opera');
INSERT INTO GENRE VALUES (27, 'Alt Classical');

INSERT INTO EMPLOYEE VALUES (9, 'Bingham', 'Donny', 'Janitor', 3, TO_DATE('12/08/1977', 'MM/DD/YYYY')
    , TO_DATE('02/28/2001', 'MM/DD/YYYY'), '123 Fake Street', 'Springfield', 'AB', 'Canada'
    , 'T1H 123', '+1 (123) 432-1234', '+1 (987) 987-8765', 'donny@chinookcorp.com');
INSERT INTO EMPLOYEE (EMPLOYEEID, LASTNAME, FIRSTNAME) VALUES (20, 'Clowny', 'Susan');

INSERT INTO CUSTOMER VALUES (60, 'Jersey', 'Samson', 'ABC Corp', '999 Wherever Road', 'Somewhere', 'TX', 'USA'
    , '98765', '+1 (123) 222-1234', '+1 (222) 333-8765', 'jersey@hulahoop.com', 5);
INSERT INTO CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL) VALUES (70, 'Orange', 'Joe', 'phillyfry@pexpress.com');

--2.4 UPDATE
UPDATE CUSTOMER SET FIRSTNAME='Robert', LASTNAME='Walter' WHERE FIRSTNAME='Aaron' AND LASTNAME='Mitchell';
UPDATE ARTIST SET NAME='CCR' WHERE NAME='Creedence Clearwater Revival';

--2.5 LIKE
SELECT * FROM INVOICE WHERE BILLINGADDRESS LIKE 'T%';

--2.6 BETWEEN
SELECT * FROM INVOICE WHERE TOTAL BETWEEN 15 AND 50;
SELECT * FROM EMPLOYEE WHERE HIREDATE BETWEEN '01-JUN-2003' AND '01-MAR-2004';

--2.7 DELETE
ALTER TABLE INVOICELINE DROP CONSTRAINT FK_INVOICELINEINVOICEID;
ALTER TABLE INVOICELINE
    ADD CONSTRAINT FK_INVOICELINEINVOICEID FOREIGN KEY(INVOICEID) REFERENCES INVOICE(INVOICEID) ON DELETE CASCADE;

ALTER TABLE INVOICE DROP CONSTRAINT FK_INVOICECUSTOMERID;
ALTER TABLE INVOICE
    ADD CONSTRAINT FK_INVOICECUSTOMERID FOREIGN KEY(CUSTOMERID) REFERENCES CUSTOMER(CUSTOMERID) ON DELETE CASCADE;

DELETE FROM CUSTOMER WHERE FIRSTNAME = 'Robert' AND LASTNAME = 'Walter';