CREATE TABLE BANK_USER (
    USER_ID INTEGER PRIMARY KEY,
    USER_NAME VARCHAR(50) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR(50) NOT NULL
);
/

CREATE TABLE BANK_ACCOUNT (
    ACCOUNT_ID INTEGER PRIMARY KEY,
    USER_ID INTEGER,
    ACCOUNT_BALANCE NUMBER (14,00),
    CONSTRAINT USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES BANK_USER (USER_ID)
);
/