--DROP TABLE EMPLOYEE;

CREATE TABLE EMPLOYEE (
	USER_ID INTEGER,
	USERNAME VARCHAR2(30) UNIQUE NOT NULL,
	PASSWORD VARCHAR2(30),
	ISMANAGER INTEGER,
	CONSTRAINT PK_EMPLOYEE PRIMARY KEY,
	CONSTRAINT CK_ISMANAGER_BOOLEAN CHECK (ISMANAGER BETWEEN 0 AND 1)
);
/

CREATE SEQUENCE SQ_EMPLOYEE_USER_ID
	START WITH 1
	INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER TR_INSERT_EMPLOYEE_USER_ID
	BEFORE INSERT ON EMPLOYEE
	FOR EACH ROW
	BEGIN
			SELECT SQ_EMPLOYEE_USER_ID INTO :NEW.USER_ID FROM DUAL;
	END;
/