DROP TABLE REIMBURSEMENT CASCADE CONSTRAINTS;
DROP TABLE EMPLOYEE CASCADE CONSTRAINTS;
DROP TABLE REIMB_IMAGES;
DROP SEQUENCE SQ_REIMB_ID;
DROP SEQUENCE SQ_EMP_ID;
DROP SEQUENCE SQ_IMAGE_ID;

CREATE TABLE EMPLOYEE (
	EMPLOYEE_ID INTEGER,
	USERNAME VARCHAR2(30) UNIQUE NOT NULL,
	PASSWORD VARCHAR2(30),
    FIRSTNAME VARCHAR2(30) NOT NULL,
    LASTNAME VARCHAR2(30) NOT NULL,
    EMAIL VARCHAR2(50) NOT NULL,
	ISMANAGER NUMBER(1) NOT NULL,
	CONSTRAINT PK_EMPLOYEE PRIMARY KEY (EMPLOYEE_ID),
	CONSTRAINT CK_ISMANAGER_BOOLEAN CHECK (ISMANAGER BETWEEN 0 AND 1)
);
/

CREATE TABLE REIMBURSEMENT (
    REIMBURSEMENT_ID INTEGER,
    DATETIMESTAMP TIMESTAMP(0) DEFAULT SYSTIMESTAMP(0),
    REQUESTER_EMP_ID INTEGER,
    APPROVAL_STATUS VARCHAR2(30),
    DESCRIPTION_NOTE VARCHAR2(200),
    CURRENCY_VALUE NUMBER(6, 2),
    CONSTRAINT PK_REIMBURSEMENT PRIMARY KEY (REIMBURSEMENT_ID),
    CONSTRAINT FK__REIMBURSEMENT__EMPLOYEE 
        FOREIGN KEY (REQUESTER_EMP_ID)
        REFERENCES EMPLOYEE(EMPLOYEE_ID)
);
/

CREATE TABLE REIMB_IMAGES (
    IMAGE_ID INTEGER,
    REIMB_IMAGE BLOB,
    IMAGE_REIMB_ID INTEGER,
    CONSTRAINT PK_IMAGE_ID PRIMARY KEY (IMAGE_ID),
    CONSTRAINT FK_REIMB_IMAGES_REIMB
        FOREIGN KEY (IMAGE_ID)
        REFERENCES REIMBURSEMENT(REIMBURSEMENT_ID)
);
/

--SEQUENCES AND TRIGGERS
--ALL THREE TABLES HAVE AUTO-GENERATED IDS
CREATE SEQUENCE SQ_REIMB_ID
	START WITH 1
	INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER TR_INSERT_REIMB_ID
	BEFORE INSERT ON REIMBURSEMENT
	FOR EACH ROW
	BEGIN
		SELECT SQ_REIMB_ID.NEXTVAL INTO :NEW.REIMBURSEMENT_ID FROM DUAL;
	END;
/

CREATE SEQUENCE SQ_EMP_ID
	START WITH 200
	INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER TR_INSERT_EMP_ID
	BEFORE INSERT ON EMPLOYEE
	FOR EACH ROW
	BEGIN
		SELECT SQ_EMP_ID.NEXTVAL INTO :NEW.EMPLOYEE_ID FROM DUAL;
	END;
/

CREATE SEQUENCE SQ_IMAGE_ID
	START WITH 1
	INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER TR_INSERT_IMAGE_ID
	BEFORE INSERT ON REIMB_IMAGES
	FOR EACH ROW
	BEGIN
    	SELECT SQ_IMAGE_ID.NEXTVAL INTO :NEW.IMAGE_ID FROM DUAL;
	END;
/