DROP TABLE EMPLOYEE;
DROP TABLE DEPARTMENT;

CREATE TABLE DEPARTMENT (
    DEPARTMENT_ID INTEGER,
    DEPARTMENT_NAME VARCHAR2(30),
    CONSTRAINT PK_DEPARTMENT PRIMARY KEY (DEPARTMENT_ID)
);
/

CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID INTEGER,
    EMP_FIRSTNAME VARCHAR2(30),
    EMP_LASTNAME VARCHAR2(30),
    DEPARTMENT_ID INTEGER,
    SALARY NUMBER(10,2),
    EMP_EMAIL VARCHAR2(50),
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (EMPLOYEE_ID),
    CONSTRAINT FK_EMPLOYEE FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(DEPARTMENT_ID)
);
/

CREATE SEQUENCE SQ_EMP_PK
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE SQ_DEPT_PK
START WITH 1
INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER TR_INSERT_EMP_ID
BEFORE INSERT ON EMPLOYEE
FOR EACH ROW
BEGIN
    SELECT SQ_EMP_PK.NEXTVAL INTO :NEW.EMPLOYEE_ID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER TR_INSERT_DEPT_ID
BEFORE INSERT ON DEPARTMENT
FOR EACH ROW
BEGIN
    SELECT SQ_DEPT_PK.NEXTVAL INTO :NEW.DEPARTMENT_ID FROM DUAL;
END;
/

